version: '3'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - mysql
      - redis
  queue:
    build: .
    volumes:
      - .:/app
    depends_on:
      - mysql
      - redis
    command: bash ./queue.sh
  scheduler:
    build: .
    volumes:
      - .:/app
    depends_on:
      - mysql
      - redis
    command: bash ./scheduler.sh
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lime
      MYSQL_USER: default
      MYSQL_PASSWORD: secret
    volumes:
      - mysql:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - mysql
  redis:
    image: redis:5.0
    volumes:
      - redis:/data
volumes:
  mysql:
  redis:
