version: '3'
services:
  app:
    build: .
    container_name: meeting_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - mysql
      - redis
    command: ["sh", "-c", "composer install && php artisan serve --host 0.0.0.0 --port 8000"]
  mysql:
    image: mysql:8.0
    container_name: meeting_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lime
      MYSQL_USER: default
      MYSQL_PASSWORD: secret
    volumes:
      - mysql:/var/lib/mysql
  queue:
    build: .
    container_name: meeting_queue
    volumes:
      - .:/app
    depends_on:
      - mysql
      - redis
    command: bash ./queue.sh
  scheduler:
    build: .
    container_name: meeting_scheduler
    volumes:
      - .:/app
    depends_on:
      - mysql
      - redis
    command: bash ./scheduler.sh
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: meeting_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - mysql
  redis:
    image: redis:latest
    container_name: meeting_redis
    volumes:
      - redis:/data
volumes:
  mysql:
  redis: